### ISSUE TITLE
Meetup sticky dock cannot be collapsed

### ISSUE THREAD

**Issue by n-d-r-d-g** [Front-End-Coders-Mauritius/frontend.mu#148]
**Issue:**
When I click the `Attend` button on the dock, it expands to show more details but then I cannot get the dock to collapse unless I refresh the page (or click `Confirm`).

Collapsed:
![image](https://github.com/user-attachments/assets/c8de7746-d4f8-4644-a3ae-6bc1548a9d77)

Expanded:
![image](https://github.com/user-attachments/assets/8668c4d0-a436-4de8-8dce-3b1aa39c9dbc)

**Expected:**
Either add a `Collapse` or `Cancel` button to collapse the dock or enable collapse by clicking anywhere on the dock's header.

**Comment by MrSunshyne** [comment]
There used to be one, but we lost it during the astro -> nuxt migration. definitely a regression

**Comment by n-d-r-d-g** [comment]
@MrSunshyne I created a [PR](https://github.com/Front-End-Coders-Mauritius/frontend.mu/pull/153).
