### ISSUE TITLE
Speaker's github acc dissappears when hovering in light mode

### ISSUE THREAD

**Issue by the-code-raider** [Front-End-Coders-Mauritius/frontend.mu#149]
**Issue:**
The text color of the speaker's GitHub account is white when hovering in light mode. 
Please find a video of the bug. :point_down: 

[hovering.webm](https://github.com/user-attachments/assets/94f452f8-047f-4401-b500-72656dd91c22)

**Comment by MrSunshyne** [comment]
Thank you for the report! I noticed two PR's fixing the same line, i merged the one with text-verse-900 ^^
