### ISSUE TITLE
Branding card layout visual bug

### ISSUE THREAD

**Issue by P-Appadoo** [Front-End-Coders-Mauritius/frontend.mu#178]
The logo is overlapping the left section of the branding card on md breakpoint.
![image](https://github.com/user-attachments/assets/cebae0c0-d70e-4fda-a654-00eb62dbbf7a)

**Comment by P-Appadoo** [comment]
@MrSunshyne i created a [PR](https://github.com/Front-End-Coders-Mauritius/frontend.mu/pull/179)

**Comment by derecklhw** [comment]
PR #179 merged. Closing issue
