### ISSUE TITLE
Feature request: Add parking availability & location on meetup detail

### ISSUE THREAD

**Issue by n-d-r-d-g** [Front-End-Coders-Mauritius/frontend.mu#223]
Currently, there is no indication on a meetup's detail page whether parking slots will be available.

Maybe we can add the availability and location of the parking slots as well next to `Seats Limit`?

![image](https://github.com/user-attachments/assets/6d57d2cb-9038-4714-aeb1-2245a80e3d90)

**Comment by MrSunshyne** [comment]
Agree! 
```ts
parking_available: boolean 
```
could be a good one to add. I will add the field in the cms

I would also encourage people to think about a better layout for the meetup page itself. I think it's not very pretty right now with the two columns and boring descriptions. 

when adding "Show location on map" and "Parking available" it'll look like a big ugly table

**Comment by n-d-r-d-g** [comment]
@MrSunshyne Indeed, there will be visual clutter. I'll think about it. We can maybe ask for the community's feedback on this via Discord?

**Comment by MrSunshyne** [comment]
I'm planning a dedicated community call focused on just the meetup page! Should be fun
