### ISSUE TITLE
Paint Bucket missing when resizing  browser

### ISSUE THREAD

**Issue by k3ii** [Front-End-Coders-Mauritius/frontend.mu#96]
The paint bucket disappear when resizing the browser.

![ponysay-paint-bucket](https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/assets/48174999/4e4cec7c-746f-481f-ae8f-3c85ea5e466b)

The other "Headers" disappear when using sidebar (when browser is resized).  
![heading](https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/assets/48174999/ce301dc2-70ba-4142-86a5-3ae90d5b86ae)

**Comment by derecklhw** [comment]
This functionality I think has been made on purpose as I have found that the HTML code for this element has a class `<div class="hidden lg:block px-4">` that controls the visibility of the element in larger screens.
